var Message = {
  text_id: "ID",
  text_success: "成功",
  text_fail: "失败",
  text_updatePassword: "修改密码",
  text_no: "序号",
  text_warn: "告警",
  text_save: "保存",
  text_del: "删除",
  text_nameIsExist: "名称已存在",
  text_nameCanUse: "名称未被使用",
  text_nameCanNotNull: "名称不能为空",
  text_type: "类型",
  text_info: "信息",
  text_detail: "详情",
  text_notice: "通知",
  text_importCompelete: "导入完毕",
  text_timeError: "时间格式有误",
  user_id: "用户ID",
  text_user_nolocked: "包含未锁定的用户！",
  menu_curr: "当前位置",
  file_name: "名称",
  file_notexist: "当前课件不存在",
  no_vod_auth_thisfile: "没有当前课件的点播权限",
  username_exists: "用户名已存在",
  userInfo_emailFormatFail: "邮箱格式不正确！",
  username_noexsits: "用户名不存在",
  username_can_use: "用户名可以使用",
  repeatLogin_confirm: "您的账号已在另一地点登录，是否强制登录?",
  repeatLogin_logined: "您的账号已在另一地点登录",
  repeatLogin_out: "您的账号在另一地点登录，您被迫下线",
  groupname_exists: "用户组已存在",
  groupname_can_use: "用户组可以使用",
  password_error: "密码错误，连续三次密码错误用户将被锁定！",
  password_error_admin: "密码错误！",
  user_havebeen_locked: "抱歉，您的账户已经被锁定！",
  code_error: "验证码错误",
  user_nopermit: "新用户未审核！",
  srcPassword_error: "原密码错误",
  param_error: "传入参数异常",
  file_write_error: "文件写入异常",
  only_support_ie: "只支持IE浏览器",
  no_vod_auth: "没有点播权限",
  no_add_auth: "没有新增权限",
  no_update_auth: "没有修改权限",
  no_delete_auth: "没有删除权限",
  no_download_auth: "没有下载权限",
  sync_success: "同步成功",
  ldap_no_sync: "LDAP未同步, 请联系管理员进行同步",
  RecServerException: "RecServer异常",
  sync_confirm: "确定要同步服务器时间吗?",
  sync_system_time_success: "同步服务器时间成功",
  sync_system_time_exception: "同步服务器时间异常",
  restartTomcat_confirm: "确定要重新启动应用吗?",
  restartSystem_confirm: "确定要重新启动服务器吗?",
  restart_success: "服务器正在重启中, 请稍后再访问",
  restart_exception: "重新启动服务器异常",
  ip_confirm: "确定要修改服务器IP吗?",
  no_auth: "权限不足",
  ldap_conn_success: "连接成功",
  ldap_conn_fail: "连接失败",
  ldap_no_conn: "未连接",
  ladp_disabled_success: "禁用LDAP服务器成功",
  ip_save_success: "IP设置成功, 服务器正在重启中, 请稍后再访问",
  ip_save_fail: "IP设置失败",
  error_404: "无效的请求地址",
  WriteException: "写入文件异常",
  log_delete_time_error: "选择月份必须距今3月以上",
  screen_config_no_select: "请选择要调整的设备!",
  time_cant_same: "开始时间与结束时间不能相同",
  equipment_no_select: "请至少选择一个设备",
  all_equipment_ex: "没有可操作的设备",
  confirm_stop_record: "确定要关闭录制吗?",
  recordex_recording: "已经存在录制的任务, 录制任务失败!",
  recordex_frequently: "点击频率太过频繁！请3秒钟后再进行录制！",
  recordex_spaceLess5Per: "硬盘空间少于5%, 录制任务失败!",
  recordCut_time_error: "无效的分片时间",
  multiPort_error: "高低质量组播端口号相差不能小于20",
  opt_success: "操作成功",
  opt_fail: "操作失败！",
  user_unlock_confirm: "您确定解锁么？",
  conflict_time: "预约时间冲突",
  error_recordPlan_time: "错误的预约时间",
  adjustScreen_setControlprotecolRestart:
    "设置遥控协议，编码卡将重启而暂时无法使用，是否继续？",
  confirm_yes: "确定",
  confirm_no: "取消",
  opting: "操作中 ...",
  refreshing: "刷新中 ...",
  deleting: "删除中 ...",
  float_loading: "数据加载中 ...",
  float_logining: "正在登录中 ...",
  float_saving: "正在保存中 ...",
  pageLoading: "页面加载中 ...",
  recording: "正在录制中",
  title_addUser: "新增用户",
  title_updateUser: "修改用户",
  title_deleteUser: "删除用户",
  title_addUsergroup: "新增用户组",
  title_updateUsergroup: "修改用户组",
  title_deleteUsergroup: "修改用户组",
  title_addFileType: "新增文件分类",
  title_updateFileType: "修改文件分类",
  title_updateFile: "修改文件",
  title_deatilInfo: "详细信息",
  title_publishBB: "发布BlackBoard",
  title_authManager: "权限管理",
  title_ldapSync: "LDAP同步",
  title_warn: "警告",
  title_safeguardLog: "日志维护",
  title_safeguardWarnLog: "告警日志维护",
  title_screen_config: "屏幕调整",
  title_adv_record: "高级录制",
  title_addGroup: "新增文件组",
  title_updateGroup: "修改文件组",
  title_addMediaFile: "添加文件",
  no_warn: "无警告信息",
  space_warn: "录制空间只剩余{0}MB！",
  ldap_conn_error: "LDAP连接失败",
  ldap_password_error: "LDAP密码错误",
  sync_success: "LDAP同步成功",
  sync_check_error: "LDAP同步失败，请确认配置的LDAP服务器信息正确",
  sync_success_self: "LDAP同步成功，您登录的LDAP用户名已不存在，请重新登录",
  user_userName: "用户名",
  msg_noData: "无数据",
  title_auth: "权限管理",
  add_noUserName: "请先输入用户名!",
  add_success: "新增成功!",
  update_success: "操作成功!",
  update_noSelect: "请选择一条记录!",
  update_moreSelect: "只能选择一条记录!",
  del_noSelect: "请选择一条记录!",
  del_confirm: "确定要删除吗?",
  del_success: "删除成功!",
  remove_confirm: "确定要从当前分类移除吗?",
  remove_success: "移除成功!",
  file_pass_confirm: "确定审批通过吗？",
  file_pass_success: "审批成功",
  del_success_self: "删除成功，您登录的用户名已不存在，请重新登录",
  system_cant_delete: "不能删除系统配置",
  look_noSelect: "请选择一条记录!",
  look_moreSelect: "只能选择一条记录!",
  save_success: "保存成功",
  page_total: "共",
  page_no: "第",
  page_page: "页",
  page_line: "条",
  page_firstPage: "第一页",
  page_prevPage: "上一页",
  page_nextPage: "下一页",
  page_lastPage: "最后一页",
  page_avgPage: "每页",
  select_header: "--请选择--",
  ta_maxCharTip: "您还可以输入{0}个字符",
  vf_existPort: "已存在的端口号",
  vf_Currency: "只能输入货币格式",
  vf_Number: "只能输入数字",
  vf_Integer: "只能输入整数",
  vf_Double: "只能输入小数",
  vf_English: "只能输入英文",
  vf_Chinese: "只能输入中文",
  vf_require: "必须填写",
  vf_empty: "不能为空",
  vf_minLen: "长度必须大于{0}个字符",
  vf_maxLen: "长度必须小于{0}个字符",
  vf_fixLen: "长度不足{0}位",
  vf_betweenLen: "长度必须在{0}与{1}个字符之间",
  vf_errorFormat: "格式有误",
  vf_noSamePassword: "两次输入密码不一致",
  vf_Name: "不能包含如下非法字符 \\ \" ' < > & % /",
  vf_BetweenRange: "输入有误(范围在{0}~{1}之间)",
  au_title: "上传文件",
  au_remove: "已删除",
  au_upload: "上传中",
  au_upload_complete: "上传完毕",
  au_done: "上传完成, 请重新启动服务器, 完成系统的升级。",
  au_error: "上传失败, 请稍候再试",
  au_btnAdd: "浏览",
  au_btnUpload: "上传",
  au_btnClean: "清空",
  au_existsFile: "文件不能重复上传",
  au_onlyOneFileUpload: "只能上传一个文件",
  file_sync_success: "文件同步成功",
  timeout: "请求超时，请稍后重试",
  auto_close: "({0}秒后自动关闭)",
  db_exception: "数据异常, 请稍候再试!",
  date_string: "{0}年{1}月{2}日 星期{3}",
  week: ["日", "一", "二", "三", "四", "五", "六"],
  comp_time_equal: "当前服务器时间与本机时间一致",
  comp_time_faster: "当前服务器时间比本机时间快 ",
  comp_time_slow: "当前服务器时间比本机时间慢 ",
  date_year: "年",
  date_month: "月",
  date_day: "日",
  date_date: "天",
  date_hour: "时",
  date_minute: "分",
  date_second: "秒",
  file_recording: "无法删除录制中文件",
  file_chooseFile: "请选择上传的文件",
  file_isNotImage: "请选择有效的图片文件",
  title_auth_set: "权限设置",
  filegroup_addfile: "添加课件",
  logexport_warn: "每次最多导出10万条记录",
  /** nodeServer **/
  nodeServer_addNode: "新增节点服务器",
  nodeServer_updateNode: "修改节点服务器",
  nodeServer_nameexists: "节点名称已存在",
  nodeServer_namecanuse: "节点名称可用",
  nodeServer_namecannotnull: "节点名称不能为空",
  nodeServer_ipvodexists: "该节点IP已存在于点播节点或主控节点中",
  nodeServer_ipliveexists: "该直播节点IP已存在",
  nodeServer_iperror: "节点IP格式有误",
  nodeServer_ipcanuse: "节点IP可用",
  nodeServer_ipcannotnull: "节点IP不能为空",
  nodeServer_connectfail: "启用失败",
  nodeServer_restartfail: "重启失败",
  nodeServer_ipisnotlivenode: "获取不到该服务器的节点信息",
  nodeServer_suredisconnode: "确定断开节点服务器？",
  nodeServer_sureconnode: "确认启用节点服务器？",
  nodeServer_surerestartnode: "确认重启节点服务器？",
  nodeServer_unknowNodeIp: "不是有效的直播节点",
  nodeServer_onlyonemainvod:
    "只能存在一个主控点播节点或此节点已在点播节点中使用",
  nodeServer_chooseNodeServer: "请选择节点类型",
  /** position **/
  position_nameexist: "名称已存在",
  position_cannotnull: "名称不能为空",
  position_title_add: "新增位置信息",
  position_title_update: "修改位置信息",
  position_pa_manager: "区域管理",
  pasition_defaultDelErr: "默认位置不能删除",
  pasition_pa_defaultDelErr: "默认区域不能删除",
  pasition_pa_delFailInfo: "请先删除关联的位置信息",
  pasition_pa_chooseArea: "请选择区域",
  pasition_chooseArea: "请选择所属区域位置",
  /** recServer **/
  recServer_add: "添加录播服务器",
  recServer_update: "修改录播服务器",
  recServer_sure_restart: "确定重启该录播服务器？",
  recServer_sure_reconnect: "确定连接该录播服务器？",
  recServer_room_info: "关联教室信息",
  recServer_restart_fail: "重启录播服务器失败",
  recServer_restart_recording: "重启录播服务器失败，该录播下有教室正在录制中",
  recServer_ip_error: "IP地址格式有误",
  recServer_isExist: "该录播已存在",
  recServer_hasNotInfo: "未获取到该IP地址上相关录播信息",
  recServer_ipNotNull: "IP地址不能为空",
  recServer_ipIsExist: "该录播服务器已存在",
  recServer_ipError: "IP地址格式有误",
  recServer_ipcanuse: "录播可用",
  recServer_delFail: "所选录播服务器部分正在使用，无法删除",
  recServer_isRoomUse: "当前录播正在被教室使用，不能修改",
  recServer_userPasswd_notNull: "用户名和密码不能为空",
  recServer_checkRightFail: "服务器鉴权失败，请确认用户名和密码正确",
  recServer_reconnect_fail: "连接服务器失败",
  /** lesson_ctime **/
  lesson_addLesson: "添加课表",
  lesson_upLesson: "修改课表",
  lesson_selectRoom: "请选择教室",
  lesson_dateNotNull: "日期不能为空",
  lesson_timeNotNull: "开始时间和结束时间不能为空",
  lesson_time_error: "开始时间或者结束时间不是有效的时间",
  lesson_selectCTime: "请选择课时",
  lesson_startNotBigEnd: "请选择课时",
  lesson_ctimeIsUse: "该课时正在使用中，无法删除",
  lesson_sureClearLesson: "确认清除课表？",
  ctime_setting: "课时设置",
  ctime_startTimeNotNull: "开始时间不能为空",
  ctime_endTimeNotNull: "开始时间不能为空",
  ctime_isConfict: "该课时与已存在课时时间冲突",
  ctime_startBigEndError: "开始时间不能大于结束时间",
  /** record **/
  record_selectRoom: "请选择教室",
  record_recNameNotNull: "录制名不能为空",
  record_recTimeNotNull: "预约开始时间和结束时间不能为空",
  record_startTimeError: "预约开始时间格式有误",
  record_endTimeError: "预约结束时间格式有误",
  record_startBigEndError: "预约开始时间不能晚于结束时间",
  record_nowBigStartError: "预约时间不能早于当前服务器时间",
  record_isConfict: "当前计划任务与已存在计划任务或者课表冲突",
  record_roomNoRecServer: "该教室未配置录播服务器",
  record_roomIsExist: "该教室已存在",
  record_chooseRecSer: "请选择录播服务器",
  record_chooseRecChannel: "请选择录播通道",
  record_recChaIsUse: "该录播通道已被使用",
  record_encoder1NotNull: "主编码器IP不能为空",
  record_encoder1IpError: "主编码器的IP地址格式有误",
  record_encoder2IpError: "VGA编码器的IP地址格式有误",
  record_encoder3IpError: "编码器1的IP地址格式有误",
  record_encoder4IpError: "编码器2的IP地址格式有误",
  record_encoder5IpError: "编码器3的IP地址格式有误",
  record_encoder6IpError: "编码器4的IP地址格式有误",
  record_streamNotNull: "请配置码率",
  record_selectPublishCourse: "请选择发布课程",
  /** room **/
  room_noRecInfo: "教室没有配置录播服务器，跳过此录制相关操作",
  room_disConn: "教室未连接，无法执行录制相关操作",
  room_disConn_suspend: "教室未连接，无法暂停录制",
  room_disConn_stop: "教室未连接，无法停止录制",
  room_disConn_record: "教室未连接，无法录制",
  room_disConn_goonrecord: "教室未连接，无法继续录制",
  room_recordFail: "录制失败，可能是通讯失败或其他问题",
  room_stopRecordFail: "停止录制失败，可能是通讯失败或其他问题",
  room_suspendRecordFail: "暂停录制失败，可能是通讯失败或其他问题",
  room_goonRecordFail: "继续录制失败，可能是通讯失败或其他问题",
  room_isUseDelFail: "所选教室正在被使用，无法删除",
  room_isrecord: "该教室当前正在录制或暂停录制中",
  room_setFailBecauRecord: "该教室正在录制或暂停录制中，无法修改教室通道信息",
  room_setRoomChannelFail: "设置教室通道信息失败，请检测录播的连接状态",
  room_encoderError: "教室编码器连接异常，执行录制或继续录制操作失败",
  /*用户审核*/
  user_review_pass: "确定通过吗?",
  user_review_refuse: "确定拒绝吗?",
  user_review_notice: "当前注册用户未审核人数:{0}",
  file_review_notice: "当前未审批课件数:{0}",
  dis_nodeServer_notice: "当前未连接直播节点数:{0}",
  dis_recServer_notice: "当前未连接录播数:{0}",
  dis_room_notice: "当前未连接教室数:{0}",
  dis_encoder_notice: "当前未连接编码器数:{0}",
  warn_info_notice: "当前告警信息数:{0}",
  file_all: "全部文件",
  /* netStorage Config added by xuzhuguang20120302 */
  save_failure: "保存失败",
  opt_netstorage_failure: "网存操作失败",
  device_busy: "设备被占用，请稍后再试",
  iscsid_connect_failure: "连接网存失败，请检查网络和配置参数",
  iscsid_not_running: "网存服务未启动",
  iscsid_login_failure: "登入网存失败",
  iscsid_logout_failure: "登出网存失败",
  filename_exists: "文件组名已存在",
  filename_noexists: "该名称可用",
  filename_upload_notexist: "该课件不存在或者不是本地课件",
  not_all_belong_this_group: "移除完毕，某些课件属于其子分类，请从子分类移除",
  lanip_ip_cannotnull: "IP地址不能为空",
  lanip_mask_notnull: "子网掩码不能为空",
  lanip_gateway_notnull: "网关不能为空",
  lanip_ip_fail: "IP地址格式有误",
  lanip_mask_fail: "子网掩码格式有误",
  lanip_gateway_fail: "网关格式有误",
  wanip_ip_cannotnull: "IP地址不能为空",
  wanip_mask_notnull: "子网掩码不能为空",
  wanip_gateway_notnull: "网关不能为空",
  wanip_ip_fail: "IP地址格式有误",
  wanip_mask_fail: "子网掩码格式有误",
  wanip_gateway_fail: "网关格式有误",
  sure_select_templete: "请选择模板文件",
  apply_success: "成功应用该模板！",
  model_name: "模板名已经存在！",
  model_name_canuse: "模板名称可以用",
  no_temlete_exception: "未包含任何页面发布失败！",
  no_homePage_Exception: "不存在首页或历史首页已经移除，发布失败！",
  detail_morefield_exception: "超出了最大字段数！",
  sure_dec_file: "是否转码此文件？",
  fail_dec_file: "转码请求发送失败，请检查转码服务器是否可用",
  task_exists: "任务冲突！",
  success_dec_send: "转码请求已经发出！",
  node_server_restart_success_send: "直播节点将立即重启，请等待...",
  deploy_blackboard_success: "成功发布到blackboard平台！",
  deploy_blackboard_fail: "发布到blackboard平台上失败！",
  blackboard_url_nonull: "Blackboard地址不能为空",
  blackboard_url_fail: "Blackboard地址格式有误",
  no_course_error: "发布的课程名必须选择！",
  no_suit_course_edit: "该课件不支持编辑！",
  not_a_number_exception: "顺序必须为数字",
  please_select_file_version: "请选择编辑版本后再预览!",
  no_auth_for_edit: "您没有权限编辑此课件！",
  no_suit_courses_edit: "所选的记录包含不支持合并的课件，请重新选择！",
  contains_unlocal_course: "所选课件包含非本地课件，不能进行合并！",
  contains_unlocal_edit: "您选择的课件为非本地课件，不能进行编辑,请重新选择",
  more_courses_merger_exception: "必须选择少于5个课件进行合并，请重试！",
  set_search_success: "设置搜索结果展示页面成功！",
  search_page_exception: "不能将首页设置为搜索结果展示页面",
  notContainsanySearchSection:
    "该页面不包含任何搜索类型区段，请在区段处理配置！",
  file_is_locked: "该课件处于编辑中，待解锁后再进行操作！",
  delete_contains_locked: "您删除的课件中包含锁定课件，不能进行删除操作！",
  save_auth_success: "修改权限成功！",
  select_file_for_del: "必须选择一个版本删除！",
  delete_origin_exception: "原版不能删除！",
  delete_version_success: "已经删除！",
  file_over_flow: "附件个数超出了范围！",
  killtranserversuccess: "成功停止转码器！",
  killtranserverfail: "失败停止转码器！",
  disabledOperationFunc: "该文件正在处于转码中，禁止操作！",
  forbiddenDeployBlackboard: "非本地课件禁止发布到blackboard平台！",
  /* keyListen */
  keyListen_loginMax: "服务器已经达到最大 在线人数，请稍后再试",
  keyListen_maxLiveUser: "服务器已经达到最大直播人数，请稍后再试",
  have_noauth_tobackstage: "您没有进入后台的权限！",
  /* DBBackup */
  delete_db_backup: "删除成功!",
  db_backup_success: "备份成功!",
  restotation_backup_success: "恢复成功!",
  delDBBackup_file: "确认要删除数据库备份文件?",
  restotationDBBackup_file:
    "恢复备份数据库信息将会还原到备份点,请确认当前是否有业务进行,以免数据丢失,确认要恢复数据库备份文件?",
  register_bbs_success: "注册成功!",
  register_bbs_fail: "注册失败!",
  month: [
    "一月",
    "二月",
    "三月",
    "四月",
    "五月",
    "六月",
    "七月",
    "八月",
    "九月",
    "十月",
    "十一月",
    "十二月",
  ],
  lesson_param_error: "时间格式有误，请重新输入！",
  ftp_ip_error: "IP格式错误",
  connect_success: "连接成功！",
  connect_failed: "连接失败！",
  title_ftp_upload: "FTP上传",
  lesson_delay_start_cross: "提前开始时间不能大于10分钟!",
  lesson_delay_end_cross: "推迟结束时间不能大于30分钟！",
  file_no_uplaod: "文件未上传至媒体中心",
  ftp_ip_null: "请输入IP地址！",
  ftp_port_null: "请输入端口!",
  ftp_username_null: "请输入用户名!",
  ftp_password_null: "请输入密码！",
  ftp_uploading: "上传中...",
  ftp_start_upload_success: "开始上传成功！",
  ftp_start_upload_failed: "开始上传失败！",
  record_encoder1BitError: "请选择主编码器码率！",
  record_encoder22BitError: "请选择辅助编码器1码率！",
  record_encoder3BitError: "请选择VGA编码器码率！",
  record_encoder4BitError: "请选择辅助编码器2码率！",
  ftp_no_hd_vedio: "所选课件中包含高清未上传完成的课件，请重新选择！",
  schoolTerm_NotNull: "学期不能为空",
  courseCode_NotNull: "课程代码不能为空",
  room_live_fail: "当前教室未开启直播或没有直播任务",
  room_live_noAuth: "没有直播权限，请联系管理员授权",
  file_del_hasSD: "课件未上传完全,不能删除!",
  live_closed: "课堂直播已关闭,页面将关闭!",
  file_reupload_confirm: "您确定重新上传该课件吗?",
  file_reupload_recording: "课件未录制完成，不能上传!",
  file_reupload_file_unfind: "录播服务器上不存在该课件,上传失败!",
  dynamic: function (key, value) {
    if (key == "") {
      return "";
    }
    var msg = Message[key];
    if (!msg) {
      return key;
    }
    if (msg.indexOf("{") != -1) {
      if (typeof value == "object") {
        for (var i = 0; i < value.length; i++) {
          if (typeof value == "object" || typeof value == "string") {
            value[i] = value[i].toString();
            if (value[i].charAt(0) == "#") {
              value[i] = Message[value[i].substring(1)];
            }
            if (!value[i]) value[i] = "";
          }
          msg = msg.replace("{" + i + "}", value[i]);
        }
      } else if (typeof value == "string") {
        if (value.charAt(0) == "#") {
          value = Message[value.substring(1)];
        }
        if (!value) value = "";
        msg = msg.replace("{0}", value);
      } else {
        msg = msg.replace("{0}", value);
      }
    }
    return msg;
  },

  dateString: function (dateString) {
    var year, month, day, week;
    if (dateString) {
      var dateStrings = dateString.split("-");
      year = dateStrings[0];
      month = dateStrings[1];
      day = dateStrings[2];
      week = dateStrings[3];
    } else {
      var date = new Date();
      year = date.getFullYear();
      month = date.getMonth() + 1;
      day = date.getDate();
      week = date.getDay();
    }

    return Message.dynamic("date_string", [
      year,
      month,
      day,
      Message.week[week],
    ]);
  },
};
